[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = true

[programs.devnet]
worker_verifier_stake = "9t83ttKm1xKRUySGN77K1fHeeJARA9ASzkqKJzhXoRsA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet="/Users/Qiaice/Documents/code/solanaProject/new-token/nVyjcxVWTddPkUF74VbrfByNKyGf2m3Kv4fmyQJNiyi.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
