[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
redeem = "BBLMZ2CV1qdiC7joGBgTEy4oS36dkJqvBWtBhh6XLAG2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# wallet = "~/.config/solana/id.json"
wallet="/Users/Qiaice/Documents/code/solanaProject/new-token/nVyjcxVWTddPkUF74VbrfByNKyGf2m3Kv4fmyQJNiyi.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
